### ISSUE TITLE
@sporcina needs a bio

### ISSUE THREAD

**Issue by sporcina** [githubteacher/developers-2015-12-01#10]
I think @sporcina needs a bio in this repository.  It should include the the following information:
[ ] Name
[ ] Occupation
[ ] Location
[ ] twitter
[ ] linkedin

And:
[ ] It should be called `sporcina.md`
[ ] It should live in the `docs` folder

**Comment by TrevorTheIntuitCoder** [comment]
You should also include your twitter handle @sporcina

**Comment by sporcina** [comment]
Good idea :)
